name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  provider: ^6.1.2
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  firebase_dynamic_links: ^5.5.7
  app_links: ^5.0.0
  skeleton_loader: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/Logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: FontMAIN
      fonts:
        - asset: assets/Fonts/Manrope-ExtraBold.ttf
